plugins:
  - checksum: 6ffe753a8147370bfffd39ead0b50466b4b9c80be4d273c8aac9ff5e5a24a4b1de49548ef9e4e4806bbb55ed8c9aad5d443c8757041af3546c3aca948cea1e95
    path: .yarn/plugins/@yarnpkg/plugin-yarnpnp2nix.cjs
    spec: "https://github.com/madjam002/yarnpnp2nix/raw/master/plugin/dist/plugin-yarnpnp2nix.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.27.cjs
