# This file is generated by running "yarn install" inside your project.
# It is essentially a version of yarn.lock that Nix can better understand
# Manual changes WILL be lost - proceed with caution!
let
  packages = {
    "@babel/code-frame@npm:7.18.6" = {
      name = "@babel/code-frame";
      reference = "npm:7.18.6";
      linkType = "HARD";
      outputName = "babel-code-frame-7.18.6-25229a7e34";
      outputHash = "eb27d165ea1c7c23e71a2a6f64225fe0ca0b2a39f5c0b57fda2a62dfa845799ca94886b08014f8fd4a711538cc6b1c89b9fc1dca6a5148893932bc03412ca848";
      flatName = "code-frame";
      languageName = "node";
      scope = "babel";
      descriptorRange = "npm:^7.0.0";
      checksum = "9/eb27d165ea1c7c23e71a2a6f64225fe0ca0b2a39f5c0b57fda2a62dfa845799ca94886b08014f8fd4a711538cc6b1c89b9fc1dca6a5148893932bc03412ca848";
      dependencies = {
        "@babel/highlight" = packages."@babel/highlight@npm:7.18.6";
      };
    };
    "@babel/helper-validator-identifier@npm:7.19.1" = {
      name = "@babel/helper-validator-identifier";
      reference = "npm:7.19.1";
      linkType = "HARD";
      outputName = "babel-helper-validator-identifier-7.19.1-d84f19e1dc";
      outputHash = "089fdf605ee8dfa3004cd84c69e655ff9ab8bdb4e7fa02bf0012db728c6247acb599ca1118d2f9124d7b417fc5793ee348f2da8bc64be230b3b13ba7cd4364cc";
      flatName = "helper-validator-identifier";
      languageName = "node";
      scope = "babel";
      descriptorRange = "npm:^7.18.6";
      checksum = "9/089fdf605ee8dfa3004cd84c69e655ff9ab8bdb4e7fa02bf0012db728c6247acb599ca1118d2f9124d7b417fc5793ee348f2da8bc64be230b3b13ba7cd4364cc";
    };
    "@babel/highlight@npm:7.18.6" = {
      name = "@babel/highlight";
      reference = "npm:7.18.6";
      linkType = "HARD";
      outputName = "babel-highlight-7.18.6-9d35ad2e27";
      outputHash = "b8eeb1d38327c635004b3ae946ff334bb994334a5fdd874e216e62bbe3b8f8f10c901c3795c25db7c8e49eb5a56948b9dbe38c3800c4f977016402997dacedae";
      flatName = "highlight";
      languageName = "node";
      scope = "babel";
      descriptorRange = "npm:^7.18.6";
      checksum = "9/b8eeb1d38327c635004b3ae946ff334bb994334a5fdd874e216e62bbe3b8f8f10c901c3795c25db7c8e49eb5a56948b9dbe38c3800c4f977016402997dacedae";
      dependencies = {
        "@babel/helper-validator-identifier" = packages."@babel/helper-validator-identifier@npm:7.19.1";
        "chalk" = packages."chalk@npm:2.4.2";
        "js-tokens" = packages."js-tokens@npm:4.0.0";
      };
    };
    "@babel/runtime@npm:7.20.1" = {
      name = "@babel/runtime";
      reference = "npm:7.20.1";
      linkType = "HARD";
      outputName = "babel-runtime-7.20.1-8f9256f2ed";
      outputHash = "dab09323346ef2e0db0571a8d9af3bf01d290f0e97100da0874106e4aff794292755716745b593153b9436dc7471e059391cc0bd7ec9e2ec55f03c462247391e";
      flatName = "runtime";
      languageName = "node";
      scope = "babel";
      descriptorRange = "npm:^7.6.3";
      checksum = "9/dab09323346ef2e0db0571a8d9af3bf01d290f0e97100da0874106e4aff794292755716745b593153b9436dc7471e059391cc0bd7ec9e2ec55f03c462247391e";
      dependencies = {
        "regenerator-runtime" = packages."regenerator-runtime@npm:0.13.10";
      };
    };
    "@esbuild/android-arm@npm:0.15.12" = {
      name = "@esbuild/android-arm";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-android-arm-0.15.12-199f527c33";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch32);
      flatName = "android-arm";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.15.12";
    };
    "@esbuild/linux-loong64@npm:0.15.12" = {
      name = "@esbuild/linux-loong64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-linux-loong64-0.15.12-738ac6232d";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "linux-loong64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.15.12";
    };
    "@redux-saga/core@npm:1.2.1" = {
      name = "@redux-saga/core";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-core-1.2.1-26e66f51bb";
      outputHash = "6da1c29ce88c75df4df9f39cc08d6d715b625e098662693e40e907407bf30fedb5a83fb502a2315df705b417f79f1be7000c56bec057bc65c89f0159510a49e2";
      flatName = "core";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "9/6da1c29ce88c75df4df9f39cc08d6d715b625e098662693e40e907407bf30fedb5a83fb502a2315df705b417f79f1be7000c56bec057bc65c89f0159510a49e2";
      dependencies = {
        "@babel/runtime" = packages."@babel/runtime@npm:7.20.1";
        "@redux-saga/deferred" = packages."@redux-saga/deferred@npm:1.2.1";
        "@redux-saga/delay-p" = packages."@redux-saga/delay-p@npm:1.2.1";
        "@redux-saga/is" = packages."@redux-saga/is@npm:1.1.3";
        "@redux-saga/symbols" = packages."@redux-saga/symbols@npm:1.1.3";
        "@redux-saga/types" = packages."@redux-saga/types@npm:1.2.1";
        "redux" = packages."redux@npm:4.2.0";
        "typescript-tuple" = packages."typescript-tuple@npm:2.2.1";
      };
    };
    "@redux-saga/deferred@npm:1.2.1" = {
      name = "@redux-saga/deferred";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-deferred-1.2.1-ec57ca1b3b";
      outputHash = "efc2e19f5e551169d01572bac5089b76d14c939e8ccf9e4dfe6130092b72e9ac2e5b9691d03dc1fddd07fda14e0129f8a6cac3d09176aa90b928a7d35e69ab31";
      flatName = "deferred";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "9/efc2e19f5e551169d01572bac5089b76d14c939e8ccf9e4dfe6130092b72e9ac2e5b9691d03dc1fddd07fda14e0129f8a6cac3d09176aa90b928a7d35e69ab31";
    };
    "@redux-saga/delay-p@npm:1.2.1" = {
      name = "@redux-saga/delay-p";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-delay-p-1.2.1-aed55ef6d3";
      outputHash = "f68e0f21869699414198941defeaca821bb7a7a6b3704a69013eba270780d410e095f3344723dbc4f27acbb6175b4a9f984f342508a5a02f3b81819b5e3592af";
      flatName = "delay-p";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "9/f68e0f21869699414198941defeaca821bb7a7a6b3704a69013eba270780d410e095f3344723dbc4f27acbb6175b4a9f984f342508a5a02f3b81819b5e3592af";
      dependencies = {
        "@redux-saga/symbols" = packages."@redux-saga/symbols@npm:1.1.3";
      };
    };
    "@redux-saga/is@npm:1.1.3" = {
      name = "@redux-saga/is";
      reference = "npm:1.1.3";
      linkType = "HARD";
      outputName = "redux-saga-is-1.1.3-b810d8c710";
      outputHash = "99f6de35e4ab7acac3dc9117370634099e84a2c03fa1e2bb45838594f38b405294065ef53a8598ce64b67d72e3656d52ec204baa68b84b469d69e36a21e7ac36";
      flatName = "is";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.1.3";
      checksum = "9/99f6de35e4ab7acac3dc9117370634099e84a2c03fa1e2bb45838594f38b405294065ef53a8598ce64b67d72e3656d52ec204baa68b84b469d69e36a21e7ac36";
      dependencies = {
        "@redux-saga/symbols" = packages."@redux-saga/symbols@npm:1.1.3";
        "@redux-saga/types" = packages."@redux-saga/types@npm:1.2.1";
      };
    };
    "@redux-saga/symbols@npm:1.1.3" = {
      name = "@redux-saga/symbols";
      reference = "npm:1.1.3";
      linkType = "HARD";
      outputName = "redux-saga-symbols-1.1.3-d95f758fa4";
      outputHash = "716a9a8be363ce9ac6b1825a2c0fb8d7576771bedb3f9357c34c441e7604ecd2a14a28a267225035e00953125f28b261067a3f0e3f27721df1d86e48da936c19";
      flatName = "symbols";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.1.3";
      checksum = "9/716a9a8be363ce9ac6b1825a2c0fb8d7576771bedb3f9357c34c441e7604ecd2a14a28a267225035e00953125f28b261067a3f0e3f27721df1d86e48da936c19";
    };
    "@redux-saga/types@npm:1.2.1" = {
      name = "@redux-saga/types";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-types-1.2.1-e3cea8c4d4";
      outputHash = "d45f477e7ef9c319e8fb955f0d09cc386edee184447eef3c566047b7867c491291799fe95271d2bc1dd41d224ee6be25c31bc7708d9ffd4f4d4ba1c9df6208e2";
      flatName = "types";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "9/d45f477e7ef9c319e8fb955f0d09cc386edee184447eef3c566047b7867c491291799fe95271d2bc1dd41d224ee6be25c31bc7708d9ffd4f4d4ba1c9df6208e2";
    };
    "@types/fs-extra@npm:9.0.13" = {
      name = "@types/fs-extra";
      reference = "npm:9.0.13";
      linkType = "HARD";
      outputName = "types-fs-extra-9.0.13-12fb7badd7";
      outputHash = "c46cad9514da52203eeed1cd72cb4caef3540edf2f3d64116febb36a5c5028478d5d3247f3894bb967872872b5aaa2c5628802056c05cd3543562d8ee9c182a0";
      flatName = "fs-extra";
      languageName = "node";
      scope = "types";
      descriptorRange = "npm:^9.0.13";
      checksum = "9/c46cad9514da52203eeed1cd72cb4caef3540edf2f3d64116febb36a5c5028478d5d3247f3894bb967872872b5aaa2c5628802056c05cd3543562d8ee9c182a0";
      dependencies = {
        "@types/node" = packages."@types/node@npm:18.11.9";
      };
    };
    "@types/lodash@npm:4.14.187" = {
      name = "@types/lodash";
      reference = "npm:4.14.187";
      linkType = "HARD";
      outputName = "types-lodash-4.14.187-9197558232";
      outputHash = "90fc80ad884fce65f8d8bc407b4209e3bc9f3a7c70de0fa61deb680b671d314e237464ff243f06e14294edda417742f8cbd0d10406cf69fe16980e4d70a6f6d1";
      flatName = "lodash";
      languageName = "node";
      scope = "types";
      descriptorRange = "npm:^4.14.184";
      checksum = "9/90fc80ad884fce65f8d8bc407b4209e3bc9f3a7c70de0fa61deb680b671d314e237464ff243f06e14294edda417742f8cbd0d10406cf69fe16980e4d70a6f6d1";
    };
    "@types/node@npm:18.11.9" = {
      name = "@types/node";
      reference = "npm:18.11.9";
      linkType = "HARD";
      outputName = "types-node-18.11.9-d21dd6ec05";
      outputHash = "7b7d90894dd1ae9b6836e49ace5bdea55cc08806a508e38851e333f1ad77ec81ea6dca58e6a2444ad0471fee965b9908cc1ef06028eebca9c20d54729df98bab";
      flatName = "node";
      languageName = "node";
      scope = "types";
      descriptorRange = "npm:^18.7.8";
      checksum = "9/7b7d90894dd1ae9b6836e49ace5bdea55cc08806a508e38851e333f1ad77ec81ea6dca58e6a2444ad0471fee965b9908cc1ef06028eebca9c20d54729df98bab";
    };
    "@types/parse-json@npm:4.0.0" = {
      name = "@types/parse-json";
      reference = "npm:4.0.0";
      linkType = "HARD";
      outputName = "types-parse-json-4.0.0-298522afa6";
      outputHash = "bea37b307bdeb352d27a4467cac738387641c4f9dfe6c8bf559d474a036952f7b998f0ac54290f9d8765fb79e154f3941dfefbb47296a987fb55ccedf344a0e6";
      flatName = "parse-json";
      languageName = "node";
      scope = "types";
      descriptorRange = "npm:^4.0.0";
      checksum = "9/bea37b307bdeb352d27a4467cac738387641c4f9dfe6c8bf559d474a036952f7b998f0ac54290f9d8765fb79e154f3941dfefbb47296a987fb55ccedf344a0e6";
    };
    "ansi-regex@npm:6.0.1" = {
      name = "ansi-regex";
      reference = "npm:6.0.1";
      linkType = "HARD";
      outputName = "ansi-regex-6.0.1-8d663a607d";
      outputHash = "53669c3634190ead828055bcae5f0feff485fd8d7d05538d4f753ad56ffedb7aa5bcc93efaa8e99e4907ad970682413f2407cf4acac8deb1d408bc564bca9027";
      flatName = "ansi-regex";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^6.0.1";
      checksum = "9/53669c3634190ead828055bcae5f0feff485fd8d7d05538d4f753ad56ffedb7aa5bcc93efaa8e99e4907ad970682413f2407cf4acac8deb1d408bc564bca9027";
    };
    "ansi-styles@npm:3.2.1" = {
      name = "ansi-styles";
      reference = "npm:3.2.1";
      linkType = "HARD";
      outputName = "ansi-styles-3.2.1-8cb8107983";
      outputHash = "88847a8969fcf787779a2cd03e73cd85ac45cbccace293e1227445dd6452cdf11df752c5f9afdb47343439762b96ae7baad1caf848360576d60be5e92f6842ab";
      flatName = "ansi-styles";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.2.1";
      checksum = "9/88847a8969fcf787779a2cd03e73cd85ac45cbccace293e1227445dd6452cdf11df752c5f9afdb47343439762b96ae7baad1caf848360576d60be5e92f6842ab";
      dependencies = {
        "color-convert" = packages."color-convert@npm:1.9.3";
      };
    };
    "balanced-match@npm:1.0.2" = {
      name = "balanced-match";
      reference = "npm:1.0.2";
      linkType = "HARD";
      outputName = "balanced-match-1.0.2-a53c126459";
      outputHash = "9ca7fca1845f06edbd8478e209a2e8eed5bb148a021719e77affeaf0c61e45af20279e4540a9f11942acc27c078fc132ff0ebc9c16a403033cff5af3d8199f40";
      flatName = "balanced-match";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.0";
      checksum = "9/9ca7fca1845f06edbd8478e209a2e8eed5bb148a021719e77affeaf0c61e45af20279e4540a9f11942acc27c078fc132ff0ebc9c16a403033cff5af3d8199f40";
    };
    "batching-toposort@npm:1.2.0" = {
      name = "batching-toposort";
      reference = "npm:1.2.0";
      linkType = "HARD";
      outputName = "batching-toposort-1.2.0-4914114c3a";
      outputHash = "f3844dd67eba403f72285ee754078092f6f42111525184525fa98824244f9f1af0877b621e7a36ac7df7c917837421c20f4297879bb6e384f117a810e22f739a";
      flatName = "batching-toposort";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.2.0";
      checksum = "9/f3844dd67eba403f72285ee754078092f6f42111525184525fa98824244f9f1af0877b621e7a36ac7df7c917837421c20f4297879bb6e384f117a810e22f739a";
    };
    "brace-expansion@npm:1.1.11" = {
      name = "brace-expansion";
      reference = "npm:1.1.11";
      linkType = "HARD";
      outputName = "brace-expansion-1.1.11-fb95eb05ad";
      outputHash = "5ecc6da29cd3b4d49a832fd8e48f3a8b6ac058f82fe778eb6751ed30a206c5ec5171f6f632aa1946ffb4f8151136740803f620b15edca8437a9348cbb21a8ba8";
      flatName = "brace-expansion";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.1.7";
      checksum = "9/5ecc6da29cd3b4d49a832fd8e48f3a8b6ac058f82fe778eb6751ed30a206c5ec5171f6f632aa1946ffb4f8151136740803f620b15edca8437a9348cbb21a8ba8";
      dependencies = {
        "balanced-match" = packages."balanced-match@npm:1.0.2";
        "concat-map" = packages."concat-map@npm:0.0.1";
      };
    };
    "callsites@npm:3.1.0" = {
      name = "callsites";
      reference = "npm:3.1.0";
      linkType = "HARD";
      outputName = "callsites-3.1.0-268f989910";
      outputHash = "a0672a95746fb1be281d90ceedafb6584dd7c33e85bb9987d6caad53ac6eb313874fc2045230e8e08ef076e4aaa899342d99bd9c47bb1dd4f6a2740b62482ca2";
      flatName = "callsites";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.0";
      checksum = "9/a0672a95746fb1be281d90ceedafb6584dd7c33e85bb9987d6caad53ac6eb313874fc2045230e8e08ef076e4aaa899342d99bd9c47bb1dd4f6a2740b62482ca2";
    };
    "chalk@npm:2.4.2" = {
      name = "chalk";
      reference = "npm:2.4.2";
      linkType = "HARD";
      outputName = "chalk-2.4.2-3ea16dd91e";
      outputHash = "befd2fe888067cfc8ceac2e7a6a62ee763b26112479dce4ee396981288fa21d5cdf3cc1b45692c94c7c6dc3638c4dc3ee6ec1c794efdf42b02e02f93039285ec";
      flatName = "chalk";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.0";
      checksum = "9/befd2fe888067cfc8ceac2e7a6a62ee763b26112479dce4ee396981288fa21d5cdf3cc1b45692c94c7c6dc3638c4dc3ee6ec1c794efdf42b02e02f93039285ec";
      dependencies = {
        "ansi-styles" = packages."ansi-styles@npm:3.2.1";
        "escape-string-regexp" = packages."escape-string-regexp@npm:1.0.5";
        "supports-color" = packages."supports-color@npm:5.5.0";
      };
    };
    "chalk@npm:5.1.2" = {
      name = "chalk";
      reference = "npm:5.1.2";
      linkType = "HARD";
      outputName = "chalk-5.1.2-221d111371";
      outputHash = "0bfd090fccb1c5918b19bea32a8f34c5e19db774758fa0ff28883aba790d614c0e4cea5061d6a48967c2b4cc91c51b77a3f9f9cee2f4fb5d258b5bf248193739";
      flatName = "chalk";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^5.0.1";
      checksum = "9/0bfd090fccb1c5918b19bea32a8f34c5e19db774758fa0ff28883aba790d614c0e4cea5061d6a48967c2b4cc91c51b77a3f9f9cee2f4fb5d258b5bf248193739";
    };
    "color-convert@npm:1.9.3" = {
      name = "color-convert";
      reference = "npm:1.9.3";
      linkType = "HARD";
      outputName = "color-convert-1.9.3-1fe690075e";
      outputHash = "42f852d574dc58609bba286cd7d10a407e213e20515c0d5d1dd8059b3d4373cd76d1057c3a242f441f2dfc6667badeb790a792662082c8038889c9235f4cd9fa";
      flatName = "color-convert";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.9.0";
      checksum = "9/42f852d574dc58609bba286cd7d10a407e213e20515c0d5d1dd8059b3d4373cd76d1057c3a242f441f2dfc6667badeb790a792662082c8038889c9235f4cd9fa";
      dependencies = {
        "color-name" = packages."color-name@npm:1.1.3";
      };
    };
    "color-name@npm:1.1.3" = {
      name = "color-name";
      reference = "npm:1.1.3";
      linkType = "HARD";
      outputName = "color-name-1.1.3-728b7b5d39";
      outputHash = "b7313c98fd745336a5e1d64921591bcd60e4e0b3894afb56286a4793c4fd304d4a38b00b514845381215ca5ed2994be05d2e1a5a80860b996d26f5f285c77dda";
      flatName = "color-name";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.1.3";
      checksum = "9/b7313c98fd745336a5e1d64921591bcd60e4e0b3894afb56286a4793c4fd304d4a38b00b514845381215ca5ed2994be05d2e1a5a80860b996d26f5f285c77dda";
    };
    "commander@npm:9.4.1" = {
      name = "commander";
      reference = "npm:9.4.1";
      linkType = "HARD";
      outputName = "commander-9.4.1-9deffb2749";
      outputHash = "7d4c1f3bd4ad451f43fce51b9c73dc2d61fca00a9249196aa2d3d66fc46f2460c917c73ea9221c278fb8d35f496384f5125806e69108581a8e8bc673752c94e6";
      flatName = "commander";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^9.4.0";
      checksum = "9/7d4c1f3bd4ad451f43fce51b9c73dc2d61fca00a9249196aa2d3d66fc46f2460c917c73ea9221c278fb8d35f496384f5125806e69108581a8e8bc673752c94e6";
    };
    "concat-map@npm:0.0.1" = {
      name = "concat-map";
      reference = "npm:0.0.1";
      linkType = "HARD";
      outputName = "concat-map-0.0.1-85a921b7ee";
      outputHash = "88222f18b3a68b71fe4473a146c8ed3315ec0488703104319c53543ad4668af3e79418ab79e2fa8032ee04c3eb45cc478815b89877a048cc5ba34e201bc15c35";
      flatName = "concat-map";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.0.1";
      checksum = "9/88222f18b3a68b71fe4473a146c8ed3315ec0488703104319c53543ad4668af3e79418ab79e2fa8032ee04c3eb45cc478815b89877a048cc5ba34e201bc15c35";
    };
    "cosmiconfig@npm:7.0.1" = {
      name = "cosmiconfig";
      reference = "npm:7.0.1";
      linkType = "HARD";
      outputName = "cosmiconfig-7.0.1-dd19ae2403";
      outputHash = "f5b0588faeb39d1bcb846504cb6693121bf6af4d09a5a0523a9201d189a769a067db33e36d6c6fe23937cc24f9771ad0e76ecb3056a4e244697867d62aa50ec0";
      flatName = "cosmiconfig";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^7.0.1";
      checksum = "9/f5b0588faeb39d1bcb846504cb6693121bf6af4d09a5a0523a9201d189a769a067db33e36d6c6fe23937cc24f9771ad0e76ecb3056a4e244697867d62aa50ec0";
      dependencies = {
        "@types/parse-json" = packages."@types/parse-json@npm:4.0.0";
        "import-fresh" = packages."import-fresh@npm:3.3.0";
        "parse-json" = packages."parse-json@npm:5.2.0";
        "path-type" = packages."path-type@npm:4.0.0";
        "yaml" = packages."yaml@npm:1.10.2";
      };
    };
    "cross-spawn@npm:7.0.3" = {
      name = "cross-spawn";
      reference = "npm:7.0.3";
      linkType = "HARD";
      outputName = "cross-spawn-7.0.3-e4ff3e65b3";
      outputHash = "37ec685f91f04d4719892f305fa6f632aae256df7f2f3f98d5c36f2197651ad7b77851aaa2d397d19a9555f0fb89fa18f9bb3ff4b440535cc0fb4fe0a72004b9";
      flatName = "cross-spawn";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^7.0.3";
      checksum = "9/37ec685f91f04d4719892f305fa6f632aae256df7f2f3f98d5c36f2197651ad7b77851aaa2d397d19a9555f0fb89fa18f9bb3ff4b440535cc0fb4fe0a72004b9";
      dependencies = {
        "path-key" = packages."path-key@npm:3.1.1";
        "shebang-command" = packages."shebang-command@npm:2.0.0";
        "which" = packages."which@npm:2.0.2";
      };
    };
    "error-ex@npm:1.3.2" = {
      name = "error-ex";
      reference = "npm:1.3.2";
      linkType = "HARD";
      outputName = "error-ex-1.3.2-5654f80c0f";
      outputHash = "5073bf16fe13e68ffd676d0af3d4bab20e52d917af1cd7e47f61c3cc2b6ec52ec874dc45307a9db6e0b7f8cb47b9f6bb831ff468d2d696cb484a3f7caf2990da";
      flatName = "error-ex";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.3.1";
      checksum = "9/5073bf16fe13e68ffd676d0af3d4bab20e52d917af1cd7e47f61c3cc2b6ec52ec874dc45307a9db6e0b7f8cb47b9f6bb831ff468d2d696cb484a3f7caf2990da";
      dependencies = {
        "is-arrayish" = packages."is-arrayish@npm:0.2.1";
      };
    };
    "esbuild-android-64@npm:0.15.12" = {
      name = "esbuild-android-64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-android-64-0.15.12-e02bdf9f5f";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "esbuild-android-64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-android-arm64@npm:0.15.12" = {
      name = "esbuild-android-arm64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-android-arm64-0.15.12-7af64ee406";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch64);
      flatName = "esbuild-android-arm64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-darwin-64@npm:0.15.12" = {
      name = "esbuild-darwin-64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-darwin-64-0.15.12-dcb3968937";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isDarwin) && (stdenv.isx86_64);
      flatName = "esbuild-darwin-64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-darwin-arm64@npm:0.15.12" = {
      name = "esbuild-darwin-arm64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-darwin-arm64-0.15.12-de29c3ce64";
      outputHashByPlatform = {
        "aarch64-darwin" = "sha512-A1j+larPhd3E4X+a92mqLZZrFt8DXALaYzIvwx3ri/RAli0/MJ79w3L/ibYQilkbGPCsHNu03jNVW3f3r7YB9w==";
      };
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isDarwin) && (stdenv.isAarch64);
      flatName = "esbuild-darwin-arm64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-freebsd-64@npm:0.15.12" = {
      name = "esbuild-freebsd-64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-freebsd-64-0.15.12-f35d6b91ef";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "esbuild-freebsd-64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-freebsd-arm64@npm:0.15.12" = {
      name = "esbuild-freebsd-arm64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-freebsd-arm64-0.15.12-0a01572c70";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch64);
      flatName = "esbuild-freebsd-arm64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-linux-32@npm:0.15.12" = {
      name = "esbuild-linux-32";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-linux-32-0.15.12-73e2c15251";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isi686);
      flatName = "esbuild-linux-32";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-linux-64@npm:0.15.12" = {
      name = "esbuild-linux-64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-linux-64-0.15.12-1259cf7b90";
      outputHashByPlatform = {
        "x86_64-linux" = "sha512-kIMptZse6jmOwsJSvDcFMdx7YzcIxbs+fSugMr6uzwtzdUJ2CM8o4Ml/aPX9nHEkWLeYAJx3ZShODG1Wqeo8CA==";
      };
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isx86_64);
      flatName = "esbuild-linux-64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-linux-arm@npm:0.15.12" = {
      name = "esbuild-linux-arm";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-linux-arm-0.15.12-ef545c652b";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isAarch32);
      flatName = "esbuild-linux-arm";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-linux-arm64@npm:0.15.12" = {
      name = "esbuild-linux-arm64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-linux-arm64-0.15.12-c3c03c61da";
      outputHashByPlatform = {
        "aarch64-linux" = "sha512-cHIl9IcJpPcakQ1xCwOfgPquqd7U84p2oZUlrx9EvAduZZVj1voA73gjcfe2Rs+y1l6p3S+dnleqxLZosMYJmQ==";
      };
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isAarch64);
      flatName = "esbuild-linux-arm64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-linux-mips64le@npm:0.15.12" = {
      name = "esbuild-linux-mips64le";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-linux-mips64le-0.15.12-2473d5a61b";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "esbuild-linux-mips64le";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-linux-ppc64le@npm:0.15.12" = {
      name = "esbuild-linux-ppc64le";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-linux-ppc64le-0.15.12-ca7de822fc";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "esbuild-linux-ppc64le";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-linux-riscv64@npm:0.15.12" = {
      name = "esbuild-linux-riscv64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-linux-riscv64-0.15.12-4fc70b6573";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "esbuild-linux-riscv64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-linux-s390x@npm:0.15.12" = {
      name = "esbuild-linux-s390x";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-linux-s390x-0.15.12-f4c4c495f6";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "esbuild-linux-s390x";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-netbsd-64@npm:0.15.12" = {
      name = "esbuild-netbsd-64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-netbsd-64-0.15.12-de1349abcc";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "esbuild-netbsd-64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-openbsd-64@npm:0.15.12" = {
      name = "esbuild-openbsd-64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-openbsd-64-0.15.12-6046081d55";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "esbuild-openbsd-64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-register@npm:3.3.3" = {
      name = "esbuild-register";
      reference = "npm:3.3.3";
      linkType = "HARD";
      outputName = "esbuild-register-3.3.3-fac3f08bfa";
      outputHash = "7e1b1c113a3ef13b4ca7740ab972fbe22327facfa6f9f20d72a00a9c109276c1c98761bfe706c2288908c54404f1d293078948bc69b4393cee77b19186a2474e";
      flatName = "esbuild-register";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.3.3";
      checksum = "9/7e1b1c113a3ef13b4ca7740ab972fbe22327facfa6f9f20d72a00a9c109276c1c98761bfe706c2288908c54404f1d293078948bc69b4393cee77b19186a2474e";
      packagePeers = [
        "@types/esbuild"
        "esbuild"
      ];
    };
    "esbuild-register@virtual:020782a0a23141e8bbfabf10ff1c4c76fe8c3642230a40210be4975c1719aabca4ef9c3b1fbcc26700434ec995b7abddcd5e8f8fff969f16778dee087bd1702f#npm:3.3.3" = {
      name = "esbuild-register";
      reference = "virtual:020782a0a23141e8bbfabf10ff1c4c76fe8c3642230a40210be4975c1719aabca4ef9c3b1fbcc26700434ec995b7abddcd5e8f8fff969f16778dee087bd1702f#npm:3.3.3";
      canonicalPackage = packages."esbuild-register@npm:3.3.3";
      dependencies = {
        "esbuild" = packages."esbuild@npm:0.15.12";
      };
    };
    "esbuild-sunos-64@npm:0.15.12" = {
      name = "esbuild-sunos-64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-sunos-64-0.15.12-4dcea658e1";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "esbuild-sunos-64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-windows-32@npm:0.15.12" = {
      name = "esbuild-windows-32";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-windows-32-0.15.12-d27f8dbee5";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isi686);
      flatName = "esbuild-windows-32";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-windows-64@npm:0.15.12" = {
      name = "esbuild-windows-64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-windows-64-0.15.12-117b1a955a";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "esbuild-windows-64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild-windows-arm64@npm:0.15.12" = {
      name = "esbuild-windows-arm64";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-windows-arm64-0.15.12-4270ce8f2d";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch64);
      flatName = "esbuild-windows-arm64";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.15.12";
    };
    "esbuild@npm:0.15.12" = {
      name = "esbuild";
      reference = "npm:0.15.12";
      linkType = "HARD";
      outputName = "esbuild-0.15.12-0d999cf382";
      outputHashByPlatform = {
        "aarch64-darwin" = "sha512-1Agkb8PowNIrcOdADf2KmzBeEIrMTDYuWxlCyx7FoEVS1/crZhB8iW5D0xsS9fKhDdOIpHZUSQP2xLf9go7C7w==";
        "x86_64-linux" = "sha512-1Agkb8PowNIrcOdADf2KmzBeEIrMTDYuWxlCyx7FoEVS1/crZhB8iW5D0xsS9fKhDdOIpHZUSQP2xLf9go7C7w==";
        "aarch64-linux" = "sha512-1Agkb8PowNIrcOdADf2KmzBeEIrMTDYuWxlCyx7FoEVS1/crZhB8iW5D0xsS9fKhDdOIpHZUSQP2xLf9go7C7w==";
      };
      shouldBeUnplugged = true;
      flatName = "esbuild";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.15.12";
      checksum = "9/b8f269625e68bc0b0dcf82b0385a66985ab5071cd5f9a988b7023bd369ba3615027f92d3c5b07ea8768c066fa1230100f1191e09153d18f8de65218d590a6b3d";
      bin = {
        "esbuild" = "bin/esbuild";
      };
      dependencies = {
        "@esbuild/android-arm" = packages."@esbuild/android-arm@npm:0.15.12";
        "@esbuild/linux-loong64" = packages."@esbuild/linux-loong64@npm:0.15.12";
        "esbuild-android-64" = packages."esbuild-android-64@npm:0.15.12";
        "esbuild-android-arm64" = packages."esbuild-android-arm64@npm:0.15.12";
        "esbuild-darwin-64" = packages."esbuild-darwin-64@npm:0.15.12";
        "esbuild-darwin-arm64" = packages."esbuild-darwin-arm64@npm:0.15.12";
        "esbuild-freebsd-64" = packages."esbuild-freebsd-64@npm:0.15.12";
        "esbuild-freebsd-arm64" = packages."esbuild-freebsd-arm64@npm:0.15.12";
        "esbuild-linux-32" = packages."esbuild-linux-32@npm:0.15.12";
        "esbuild-linux-64" = packages."esbuild-linux-64@npm:0.15.12";
        "esbuild-linux-arm64" = packages."esbuild-linux-arm64@npm:0.15.12";
        "esbuild-linux-arm" = packages."esbuild-linux-arm@npm:0.15.12";
        "esbuild-linux-mips64le" = packages."esbuild-linux-mips64le@npm:0.15.12";
        "esbuild-linux-ppc64le" = packages."esbuild-linux-ppc64le@npm:0.15.12";
        "esbuild-linux-riscv64" = packages."esbuild-linux-riscv64@npm:0.15.12";
        "esbuild-linux-s390x" = packages."esbuild-linux-s390x@npm:0.15.12";
        "esbuild-netbsd-64" = packages."esbuild-netbsd-64@npm:0.15.12";
        "esbuild-openbsd-64" = packages."esbuild-openbsd-64@npm:0.15.12";
        "esbuild-sunos-64" = packages."esbuild-sunos-64@npm:0.15.12";
        "esbuild-windows-32" = packages."esbuild-windows-32@npm:0.15.12";
        "esbuild-windows-64" = packages."esbuild-windows-64@npm:0.15.12";
        "esbuild-windows-arm64" = packages."esbuild-windows-arm64@npm:0.15.12";
      };
    };
    "escape-string-regexp@npm:1.0.5" = {
      name = "escape-string-regexp";
      reference = "npm:1.0.5";
      linkType = "HARD";
      outputName = "escape-string-regexp-1.0.5-3284de402f";
      outputHash = "14d2c74a990b4a0ae55f299409693533a620402a6efa02b201d7e2ea60c71a516c36ccfcaf2aa604262eec6c4628bf8b9647e211fb179277cb479bd870c906fa";
      flatName = "escape-string-regexp";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.5";
      checksum = "9/14d2c74a990b4a0ae55f299409693533a620402a6efa02b201d7e2ea60c71a516c36ccfcaf2aa604262eec6c4628bf8b9647e211fb179277cb479bd870c906fa";
    };
    "eventemitter3@npm:4.0.7" = {
      name = "eventemitter3";
      reference = "npm:4.0.7";
      linkType = "HARD";
      outputName = "eventemitter3-4.0.7-7afcdd74ae";
      outputHash = "e6ecb1ac2fee59b0ba0e778564cec0a1fe0631f28a50f24aa0e7ba367e718c5f9b23156fb2c1d238bcebe7923dfff37a63c39b519121a47c7bf78c38c96febd8";
      flatName = "eventemitter3";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.7";
      checksum = "9/e6ecb1ac2fee59b0ba0e778564cec0a1fe0631f28a50f24aa0e7ba367e718c5f9b23156fb2c1d238bcebe7923dfff37a63c39b519121a47c7bf78c38c96febd8";
    };
    "execa@npm:6.1.0" = {
      name = "execa";
      reference = "npm:6.1.0";
      linkType = "HARD";
      outputName = "execa-6.1.0-be1d7f323b";
      outputHash = "ebe384facfb5c4e7007828a518fedb2d7704bd10e69d4584de4427d47ceadf1e9377203f4ca754c17e1a82a492b5eefad64dda65fa473bf756ab6de62124651e";
      flatName = "execa";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^6.1.0";
      checksum = "9/ebe384facfb5c4e7007828a518fedb2d7704bd10e69d4584de4427d47ceadf1e9377203f4ca754c17e1a82a492b5eefad64dda65fa473bf756ab6de62124651e";
      dependencies = {
        "cross-spawn" = packages."cross-spawn@npm:7.0.3";
        "get-stream" = packages."get-stream@npm:6.0.1";
        "human-signals" = packages."human-signals@npm:3.0.1";
        "is-stream" = packages."is-stream@npm:3.0.0";
        "merge-stream" = packages."merge-stream@npm:2.0.0";
        "npm-run-path" = packages."npm-run-path@npm:5.1.0";
        "onetime" = packages."onetime@npm:6.0.0";
        "signal-exit" = packages."signal-exit@npm:3.0.7";
        "strip-final-newline" = packages."strip-final-newline@npm:3.0.0";
      };
    };
    "fs-extra@npm:10.1.0" = {
      name = "fs-extra";
      reference = "npm:10.1.0";
      linkType = "HARD";
      outputName = "fs-extra-10.1.0-86573680ed";
      outputHash = "c397c1bfbb8976afb6758a96b9d5781c179b01ec843caa9f6613b8d95d95e17229d1ba7132dd811e112df5f2537bce1f68a3c0a722decc345947f133921fa3b3";
      flatName = "fs-extra";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^10.1.0";
      checksum = "9/c397c1bfbb8976afb6758a96b9d5781c179b01ec843caa9f6613b8d95d95e17229d1ba7132dd811e112df5f2537bce1f68a3c0a722decc345947f133921fa3b3";
      dependencies = {
        "graceful-fs" = packages."graceful-fs@npm:4.2.10";
        "jsonfile" = packages."jsonfile@npm:6.1.0";
        "universalify" = packages."universalify@npm:2.0.0";
      };
    };
    "fs.realpath@npm:1.0.0" = {
      name = "fs.realpath";
      reference = "npm:1.0.0";
      linkType = "HARD";
      outputName = "fs.realpath-1.0.0-c8f05d8126";
      outputHash = "477fb3547134ce67d71531a19b2597028d2efaeced56a2fcb125ba9994a4204685d256795e4a5b68e5d866d11d8d0dd9050937cb44037beb4caeb3acb75602e2";
      flatName = "fs.realpath";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.0";
      checksum = "9/477fb3547134ce67d71531a19b2597028d2efaeced56a2fcb125ba9994a4204685d256795e4a5b68e5d866d11d8d0dd9050937cb44037beb4caeb3acb75602e2";
    };
    "get-stream@npm:6.0.1" = {
      name = "get-stream";
      reference = "npm:6.0.1";
      linkType = "HARD";
      outputName = "get-stream-6.0.1-83e51a4642";
      outputHash = "20a00f890236e3dafa7cb2ca44f779d8547544a8cafd3d6e8e19f0c38c1b577273e49615c1de08cb94b6b10470539bcd1f3620ecedc0cff12ed131d9b5dc5fd2";
      flatName = "get-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^6.0.1";
      checksum = "9/20a00f890236e3dafa7cb2ca44f779d8547544a8cafd3d6e8e19f0c38c1b577273e49615c1de08cb94b6b10470539bcd1f3620ecedc0cff12ed131d9b5dc5fd2";
    };
    "glob@npm:7.2.3" = {
      name = "glob";
      reference = "npm:7.2.3";
      linkType = "HARD";
      outputName = "glob-7.2.3-2d866d17a5";
      outputHash = "c55966a5db7ed2f30976a1490f3165f9d4e20ac7cabf01b55da4cc4f8f53a4c506e6f427e469c2fbf68636200871f3acf07e159ba6d9b65e7386216b98474a34";
      flatName = "glob";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^7.1.3";
      checksum = "9/c55966a5db7ed2f30976a1490f3165f9d4e20ac7cabf01b55da4cc4f8f53a4c506e6f427e469c2fbf68636200871f3acf07e159ba6d9b65e7386216b98474a34";
      dependencies = {
        "fs.realpath" = packages."fs.realpath@npm:1.0.0";
        "inflight" = packages."inflight@npm:1.0.6";
        "inherits" = packages."inherits@npm:2.0.4";
        "minimatch" = packages."minimatch@npm:3.1.2";
        "once" = packages."once@npm:1.4.0";
        "path-is-absolute" = packages."path-is-absolute@npm:1.0.1";
      };
    };
    "graceful-fs@npm:4.2.10" = {
      name = "graceful-fs";
      reference = "npm:4.2.10";
      linkType = "HARD";
      outputName = "graceful-fs-4.2.10-79c70989ca";
      outputHash = "6b5f9b5aeaee0459b9c37bdbf9624f788703ce291d6bf2d7751f5003942e853f232ca613aec818d1ff7622379bc8b434c635bfda99db93e0b9b8da80ec3d844d";
      flatName = "graceful-fs";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.2.0";
      checksum = "9/6b5f9b5aeaee0459b9c37bdbf9624f788703ce291d6bf2d7751f5003942e853f232ca613aec818d1ff7622379bc8b434c635bfda99db93e0b9b8da80ec3d844d";
    };
    "has-flag@npm:3.0.0" = {
      name = "has-flag";
      reference = "npm:3.0.0";
      linkType = "HARD";
      outputName = "has-flag-3.0.0-16ac11fe05";
      outputHash = "b1cb757b71bca736b4f7a060d52a7914b1438d7bd7ba3cb783f71728c7a72d51520955d477d54fce75e19a859d93fadc9b707de019c141c45f2e560c48beb1f9";
      flatName = "has-flag";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.0";
      checksum = "9/b1cb757b71bca736b4f7a060d52a7914b1438d7bd7ba3cb783f71728c7a72d51520955d477d54fce75e19a859d93fadc9b707de019c141c45f2e560c48beb1f9";
    };
    "human-signals@npm:3.0.1" = {
      name = "human-signals";
      reference = "npm:3.0.1";
      linkType = "HARD";
      outputName = "human-signals-3.0.1-0c557ca74a";
      outputHash = "00cff8f78516e925bef0d0bc65dfbf8bfad876ef3dc1aeec98f2ba845b56e9a58972a9e002323ef7e6de08b2a2fc0cb9a27ddadf7fae608b2828d241d6ae32b3";
      flatName = "human-signals";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.1";
      checksum = "9/00cff8f78516e925bef0d0bc65dfbf8bfad876ef3dc1aeec98f2ba845b56e9a58972a9e002323ef7e6de08b2a2fc0cb9a27ddadf7fae608b2828d241d6ae32b3";
    };
    "immer@npm:9.0.16" = {
      name = "immer";
      reference = "npm:9.0.16";
      linkType = "HARD";
      outputName = "immer-9.0.16-426ac657bc";
      outputHash = "cba94dce2c4193ac32fc789749d7b009a7a5d922e2ffc447f1b62efa25d623836571393e920b09a9e2b352702e178a6c4e9cf9597754b43cb161f3927fbae704";
      flatName = "immer";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^9.0.15";
      checksum = "9/cba94dce2c4193ac32fc789749d7b009a7a5d922e2ffc447f1b62efa25d623836571393e920b09a9e2b352702e178a6c4e9cf9597754b43cb161f3927fbae704";
    };
    "import-fresh@npm:3.3.0" = {
      name = "import-fresh";
      reference = "npm:3.3.0";
      linkType = "HARD";
      outputName = "import-fresh-3.3.0-3e34265ca9";
      outputHash = "81ec300d4d16df0ba4f4ed99f4c7e8f312c4c6f48c100afe801deae468479cb8d8209a7c71a943b3e6def4fa0c24ad3eac34e72cb4968424930df39e8d16e9c9";
      flatName = "import-fresh";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.2.1";
      checksum = "9/81ec300d4d16df0ba4f4ed99f4c7e8f312c4c6f48c100afe801deae468479cb8d8209a7c71a943b3e6def4fa0c24ad3eac34e72cb4968424930df39e8d16e9c9";
      dependencies = {
        "parent-module" = packages."parent-module@npm:1.0.1";
        "resolve-from" = packages."resolve-from@npm:4.0.0";
      };
    };
    "inflight@npm:1.0.6" = {
      name = "inflight";
      reference = "npm:1.0.6";
      linkType = "HARD";
      outputName = "inflight-1.0.6-ccedb4b908";
      outputHash = "40d0e5db34e05d49b9ad9ac678334269745644f73206862a8dee6e50ada1c8b3e70774ce28d5e6e3b03b7b868c9d9ae1edaf6eff253fc50209e4c69decad1811";
      flatName = "inflight";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.4";
      checksum = "9/40d0e5db34e05d49b9ad9ac678334269745644f73206862a8dee6e50ada1c8b3e70774ce28d5e6e3b03b7b868c9d9ae1edaf6eff253fc50209e4c69decad1811";
      dependencies = {
        "once" = packages."once@npm:1.4.0";
        "wrappy" = packages."wrappy@npm:1.0.2";
      };
    };
    "inherits@npm:2.0.4" = {
      name = "inherits";
      reference = "npm:2.0.4";
      linkType = "HARD";
      outputName = "inherits-2.0.4-c66b3957a0";
      outputHash = "ca76c7e45ec715bfe6c1dd67b780b9a15068f37b37ab56cf8b773537b2654238469a42950f5f4d301212755e7512be888f627752e778e1863d95cfedefc8b8bd";
      flatName = "inherits";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2";
      checksum = "9/ca76c7e45ec715bfe6c1dd67b780b9a15068f37b37ab56cf8b773537b2654238469a42950f5f4d301212755e7512be888f627752e778e1863d95cfedefc8b8bd";
    };
    "is-arrayish@npm:0.2.1" = {
      name = "is-arrayish";
      reference = "npm:0.2.1";
      linkType = "HARD";
      outputName = "is-arrayish-0.2.1-23927dfb15";
      outputHash = "c701fd85259ab454cfacf4a30123e3e43542a3e60124a670e89f6e5847590ff4a6e4c0d8ccbe940df64f0001547f65856cf6a13b6528a7ce93da34cf2b2ea23d";
      flatName = "is-arrayish";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.2.1";
      checksum = "9/c701fd85259ab454cfacf4a30123e3e43542a3e60124a670e89f6e5847590ff4a6e4c0d8ccbe940df64f0001547f65856cf6a13b6528a7ce93da34cf2b2ea23d";
    };
    "is-stream@npm:3.0.0" = {
      name = "is-stream";
      reference = "npm:3.0.0";
      linkType = "HARD";
      outputName = "is-stream-3.0.0-a77ac9a62e";
      outputHash = "9cb18df7e094ff4907395e27527c6615cd7f48343d71c17af79079df642710a72c5f8d2090512d738c5b05989f124be0a6e031f8c459bb8d2f512e503d54695b";
      flatName = "is-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.0";
      checksum = "9/9cb18df7e094ff4907395e27527c6615cd7f48343d71c17af79079df642710a72c5f8d2090512d738c5b05989f124be0a6e031f8c459bb8d2f512e503d54695b";
    };
    "isexe@npm:2.0.0" = {
      name = "isexe";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "isexe-2.0.0-b58870bd2e";
      outputHash = "b37fe0a7983c0c151c7b31ca716405aaea190ac9cd6ef3f79355f4afb043ed4d3182a6addd73b20df7a0b229269737ad0daf64116821a048bfbe6b8fb7eb842c";
      flatName = "isexe";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.0";
      checksum = "9/b37fe0a7983c0c151c7b31ca716405aaea190ac9cd6ef3f79355f4afb043ed4d3182a6addd73b20df7a0b229269737ad0daf64116821a048bfbe6b8fb7eb842c";
    };
    "js-tokens@npm:4.0.0" = {
      name = "js-tokens";
      reference = "npm:4.0.0";
      linkType = "HARD";
      outputName = "js-tokens-4.0.0-0ac852e9e2";
      outputHash = "47d1c18dc6b9eed4baf1db3d81b36feb95b463201c82ffce0d7a4d65ede596ba97d6ac2468974199705db9ef8a3433606af41fc7bbe7cb25c1dd601785413d9b";
      flatName = "js-tokens";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.0";
      checksum = "9/47d1c18dc6b9eed4baf1db3d81b36feb95b463201c82ffce0d7a4d65ede596ba97d6ac2468974199705db9ef8a3433606af41fc7bbe7cb25c1dd601785413d9b";
    };
    "json-parse-even-better-errors@npm:2.3.1" = {
      name = "json-parse-even-better-errors";
      reference = "npm:2.3.1";
      linkType = "HARD";
      outputName = "json-parse-even-better-errors-2.3.1-144d62256e";
      outputHash = "ba9ec77806c99530719c8c2a26aa426f421dccd6faafb4ee32f2d71dff25aefe4d150fba814eb58be8b82e765af5e7dc8e88d1c38c7227a1304f4d20a405a67a";
      flatName = "json-parse-even-better-errors";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.3.0";
      checksum = "9/ba9ec77806c99530719c8c2a26aa426f421dccd6faafb4ee32f2d71dff25aefe4d150fba814eb58be8b82e765af5e7dc8e88d1c38c7227a1304f4d20a405a67a";
    };
    "jsonfile@npm:6.1.0" = {
      name = "jsonfile";
      reference = "npm:6.1.0";
      linkType = "HARD";
      outputName = "jsonfile-6.1.0-20a4796cee";
      outputHash = "d1fe80d443f7b3257aef1ef918231c9cf8a57127f004f74232869dfa408188b6ccf9d8a6724f7dbf7a6797355969cacfe1f2a16779f4ec636999bfaa876c13b0";
      flatName = "jsonfile";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^6.0.1";
      checksum = "9/d1fe80d443f7b3257aef1ef918231c9cf8a57127f004f74232869dfa408188b6ccf9d8a6724f7dbf7a6797355969cacfe1f2a16779f4ec636999bfaa876c13b0";
      dependencies = {
        "graceful-fs" = packages."graceful-fs@npm:4.2.10";
        "universalify" = packages."universalify@npm:2.0.0";
      };
    };
    "lines-and-columns@npm:1.2.4" = {
      name = "lines-and-columns";
      reference = "npm:1.2.4";
      linkType = "HARD";
      outputName = "lines-and-columns-1.2.4-d6c7cc5799";
      outputHash = "c0807326f935ca3bbb725fe1a90d4a15e9b58939a2e75f5e85aa28e488620088b0f110bac2c384537e3c16cf64134afc67f39dd77f9249dcf7d056400d8c303b";
      flatName = "lines-and-columns";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.1.6";
      checksum = "9/c0807326f935ca3bbb725fe1a90d4a15e9b58939a2e75f5e85aa28e488620088b0f110bac2c384537e3c16cf64134afc67f39dd77f9249dcf7d056400d8c303b";
    };
    "lodash@npm:4.17.21" = {
      name = "lodash";
      reference = "npm:4.17.21";
      linkType = "HARD";
      outputName = "lodash-4.17.21-6382451519";
      outputHash = "3ac18e92108d68f88429fcddee609e42cf2b653583d9bac22308815a4cd6b185b89a0ad0d9b0c670c371d9d6b61571a98fee6b36e1db14e52766ca253ed9cba0";
      flatName = "lodash";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.17.21";
      checksum = "9/3ac18e92108d68f88429fcddee609e42cf2b653583d9bac22308815a4cd6b185b89a0ad0d9b0c670c371d9d6b61571a98fee6b36e1db14e52766ca253ed9cba0";
    };
    "merge-stream@npm:2.0.0" = {
      name = "merge-stream";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "merge-stream-2.0.0-2ac83efea5";
      outputHash = "39a20c6f74e424ffb406cba0f4907c9ce06a85c84fb42a5628c6a39cd56fb3e70481b6f4d3412cf502cc3416c6e14d8d9ae6b2a4d461e56879350741220bd1e9";
      flatName = "merge-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.0";
      checksum = "9/39a20c6f74e424ffb406cba0f4907c9ce06a85c84fb42a5628c6a39cd56fb3e70481b6f4d3412cf502cc3416c6e14d8d9ae6b2a4d461e56879350741220bd1e9";
    };
    "mimic-fn@npm:4.0.0" = {
      name = "mimic-fn";
      reference = "npm:4.0.0";
      linkType = "HARD";
      outputName = "mimic-fn-4.0.0-feaeda79f7";
      outputHash = "6854bdfe4abeb91b19fc0d1bbec01ad065fde2d2c03c81557eb7a1ed3354c1c956962e293bd97bc110b7b24fa30a3345d8756bbbed82e458cc68a45521eb7813";
      flatName = "mimic-fn";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.0";
      checksum = "9/6854bdfe4abeb91b19fc0d1bbec01ad065fde2d2c03c81557eb7a1ed3354c1c956962e293bd97bc110b7b24fa30a3345d8756bbbed82e458cc68a45521eb7813";
    };
    "minimatch@npm:3.1.2" = {
      name = "minimatch";
      reference = "npm:3.1.2";
      linkType = "HARD";
      outputName = "minimatch-3.1.2-9405269906";
      outputHash = "97f5615ee8f7c0019277dadef7b2b81e5c60d369cb3155cbfb9da72688aef2edb652b105353ff08a6575ae95a6189d1c09a0829b9c254f60849148457c4d8a66";
      flatName = "minimatch";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.1.1";
      checksum = "9/97f5615ee8f7c0019277dadef7b2b81e5c60d369cb3155cbfb9da72688aef2edb652b105353ff08a6575ae95a6189d1c09a0829b9c254f60849148457c4d8a66";
      dependencies = {
        "brace-expansion" = packages."brace-expansion@npm:1.1.11";
      };
    };
    "nix-task@workspace:." = {
      name = "nix-task";
      reference = "workspace:.";
      linkType = "SOFT";
      outputName = "nix-task-0.0.0-020782a0a2";
      src = ./.;
      shouldBeUnplugged = true;
      flatName = "nix-task";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:.";
      bin = {
        "nix-task" = "nix-task.js";
      };
      devDependencies = {
        "@types/fs-extra" = packages."@types/fs-extra@npm:9.0.13";
        "@types/lodash" = packages."@types/lodash@npm:4.14.187";
        "@types/node" = packages."@types/node@npm:18.11.9";
        "batching-toposort" = packages."batching-toposort@npm:1.2.0";
        "chalk" = packages."chalk@npm:5.1.2";
        "commander" = packages."commander@npm:9.4.1";
        "cosmiconfig" = packages."cosmiconfig@npm:7.0.1";
        "esbuild" = packages."esbuild@npm:0.15.12";
        "esbuild-register" = packages."esbuild-register@virtual:020782a0a23141e8bbfabf10ff1c4c76fe8c3642230a40210be4975c1719aabca4ef9c3b1fbcc26700434ec995b7abddcd5e8f8fff969f16778dee087bd1702f#npm:3.3.3";
        "execa" = packages."execa@npm:6.1.0";
        "fs-extra" = packages."fs-extra@npm:10.1.0";
        "immer" = packages."immer@npm:9.0.16";
        "lodash" = packages."lodash@npm:4.17.21";
        "p-queue" = packages."p-queue@npm:7.3.4";
        "redux-saga" = packages."redux-saga@npm:1.2.1";
        "strip-ansi" = packages."strip-ansi@npm:7.0.1";
        "tmp-promise" = packages."tmp-promise@npm:3.0.3";
        "typescript" = packages."typescript@patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>::version=4.9.1-beta&hash=7f4d21";
      };
    };
    "npm-run-path@npm:5.1.0" = {
      name = "npm-run-path";
      reference = "npm:5.1.0";
      linkType = "HARD";
      outputName = "npm-run-path-5.1.0-79c0668d42";
      outputHash = "f27be5e6bba147df4c7f6869e7520a91a142c765a6d414ed1e1b111104cd8b2530befab9995c9f12482ee97eec234ba7cbb818cb16dd7a746131888528c57271";
      flatName = "npm-run-path";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^5.1.0";
      checksum = "9/f27be5e6bba147df4c7f6869e7520a91a142c765a6d414ed1e1b111104cd8b2530befab9995c9f12482ee97eec234ba7cbb818cb16dd7a746131888528c57271";
      dependencies = {
        "path-key" = packages."path-key@npm:4.0.0";
      };
    };
    "once@npm:1.4.0" = {
      name = "once";
      reference = "npm:1.4.0";
      linkType = "HARD";
      outputName = "once-1.4.0-ccf03ef07a";
      outputHash = "12d5c6ece331855387577e71c96ab5b60269390b131cf9403494206274fa520221c88f8b8d431d7227d080127730460da8907c402ab4142e592c34aacb5c9817";
      flatName = "once";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.3.0";
      checksum = "9/12d5c6ece331855387577e71c96ab5b60269390b131cf9403494206274fa520221c88f8b8d431d7227d080127730460da8907c402ab4142e592c34aacb5c9817";
      dependencies = {
        "wrappy" = packages."wrappy@npm:1.0.2";
      };
    };
    "onetime@npm:6.0.0" = {
      name = "onetime";
      reference = "npm:6.0.0";
      linkType = "HARD";
      outputName = "onetime-6.0.0-4f3684e29a";
      outputHash = "652280f3e6536e1393b5bd59b26ae46522cb40459ed39662bc287b57f374ba299e7025b0510f068dfb10cceec2fb86b369ffcc5eef5f9b9c28d21ccd2476364a";
      flatName = "onetime";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^6.0.0";
      checksum = "9/652280f3e6536e1393b5bd59b26ae46522cb40459ed39662bc287b57f374ba299e7025b0510f068dfb10cceec2fb86b369ffcc5eef5f9b9c28d21ccd2476364a";
      dependencies = {
        "mimic-fn" = packages."mimic-fn@npm:4.0.0";
      };
    };
    "p-queue@npm:7.3.4" = {
      name = "p-queue";
      reference = "npm:7.3.4";
      linkType = "HARD";
      outputName = "p-queue-7.3.4-c746a7f1ae";
      outputHash = "f2a163b1ac35ea31c19b1b7dee2223126605dd945b29c265427a5d1840fe35b231e8e7db4e93e7c8d9e074b4e3abd9eceaea1f5c820634dfe3a972da2fa6e914";
      flatName = "p-queue";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^7.3.4";
      checksum = "9/f2a163b1ac35ea31c19b1b7dee2223126605dd945b29c265427a5d1840fe35b231e8e7db4e93e7c8d9e074b4e3abd9eceaea1f5c820634dfe3a972da2fa6e914";
      dependencies = {
        "eventemitter3" = packages."eventemitter3@npm:4.0.7";
        "p-timeout" = packages."p-timeout@npm:5.1.0";
      };
    };
    "p-timeout@npm:5.1.0" = {
      name = "p-timeout";
      reference = "npm:5.1.0";
      linkType = "HARD";
      outputName = "p-timeout-5.1.0-11ca554b60";
      outputHash = "76a7859acee180296d0f4a4650fa70b03973ec13ce73fa3a44540c19634a221592d1c05efff339e1bf76cc0b66bcc96fe51988ac11d451aa5cb13fbf752a2d2a";
      flatName = "p-timeout";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^5.0.2";
      checksum = "9/76a7859acee180296d0f4a4650fa70b03973ec13ce73fa3a44540c19634a221592d1c05efff339e1bf76cc0b66bcc96fe51988ac11d451aa5cb13fbf752a2d2a";
    };
    "parent-module@npm:1.0.1" = {
      name = "parent-module";
      reference = "npm:1.0.1";
      linkType = "HARD";
      outputName = "parent-module-1.0.1-1fae11b095";
      outputHash = "ac26e4d08ec70f2e03c7e7b80c384fc3201576c04102ecf8cfef29051980208bd41a552802f1c46d6f3c1f0f864ce4f3cfc1f3077c19561a08df214d7b3fe3ec";
      flatName = "parent-module";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.0";
      checksum = "9/ac26e4d08ec70f2e03c7e7b80c384fc3201576c04102ecf8cfef29051980208bd41a552802f1c46d6f3c1f0f864ce4f3cfc1f3077c19561a08df214d7b3fe3ec";
      dependencies = {
        "callsites" = packages."callsites@npm:3.1.0";
      };
    };
    "parse-json@npm:5.2.0" = {
      name = "parse-json";
      reference = "npm:5.2.0";
      linkType = "HARD";
      outputName = "parse-json-5.2.0-00a63b1199";
      outputHash = "0c094e234bde1a643949a0ab6e46f12dfc8c11b38b3b7fd676a6f13499e208fe290ff94a48450abb7d043b556a31e1b4b781ced9ee3a08ac37cb250479396e50";
      flatName = "parse-json";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^5.0.0";
      checksum = "9/0c094e234bde1a643949a0ab6e46f12dfc8c11b38b3b7fd676a6f13499e208fe290ff94a48450abb7d043b556a31e1b4b781ced9ee3a08ac37cb250479396e50";
      dependencies = {
        "@babel/code-frame" = packages."@babel/code-frame@npm:7.18.6";
        "error-ex" = packages."error-ex@npm:1.3.2";
        "json-parse-even-better-errors" = packages."json-parse-even-better-errors@npm:2.3.1";
        "lines-and-columns" = packages."lines-and-columns@npm:1.2.4";
      };
    };
    "path-is-absolute@npm:1.0.1" = {
      name = "path-is-absolute";
      reference = "npm:1.0.1";
      linkType = "HARD";
      outputName = "path-is-absolute-1.0.1-31bc695ffd";
      outputHash = "6bb8fef4324c3f744e5d216980aa053095e1fc533d40fa47f9c1adc16be7fa52d3c4858370c7685406c32ab143a4dca0798f2e2c0f57d7937af66d8dd79267f6";
      flatName = "path-is-absolute";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.0";
      checksum = "9/6bb8fef4324c3f744e5d216980aa053095e1fc533d40fa47f9c1adc16be7fa52d3c4858370c7685406c32ab143a4dca0798f2e2c0f57d7937af66d8dd79267f6";
    };
    "path-key@npm:3.1.1" = {
      name = "path-key";
      reference = "npm:3.1.1";
      linkType = "HARD";
      outputName = "path-key-3.1.1-0e66ea8321";
      outputHash = "93ee8a32e3be43548ece14eba2620bf5164884d0cc1aa3615d136567a39e02066c9b5aeb5b6747d766af55936151c95d9371ba46d4fcf361db9691505650c001";
      flatName = "path-key";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.1.0";
      checksum = "9/93ee8a32e3be43548ece14eba2620bf5164884d0cc1aa3615d136567a39e02066c9b5aeb5b6747d766af55936151c95d9371ba46d4fcf361db9691505650c001";
    };
    "path-key@npm:4.0.0" = {
      name = "path-key";
      reference = "npm:4.0.0";
      linkType = "HARD";
      outputName = "path-key-4.0.0-2bce99f089";
      outputHash = "bcf9db787d460568a6f348d00be2e88cafa9eef1b98d7cbd86f8d9d7c760a4d16ed54a1ad6a4bd436c4fc19f3f47c99b870016b304bfdca56b4cbcdb722b2a0c";
      flatName = "path-key";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.0";
      checksum = "9/bcf9db787d460568a6f348d00be2e88cafa9eef1b98d7cbd86f8d9d7c760a4d16ed54a1ad6a4bd436c4fc19f3f47c99b870016b304bfdca56b4cbcdb722b2a0c";
    };
    "path-type@npm:4.0.0" = {
      name = "path-type";
      reference = "npm:4.0.0";
      linkType = "HARD";
      outputName = "path-type-4.0.0-10d47fc86a";
      outputHash = "6a9330ad8d96f31e929feb414cde2959078379ba5a48c9e3eab34f280d7850eec6a0fa3ed5be9150e9e4d7df5139c1ae92f891b18167528553a11382d8f54183";
      flatName = "path-type";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.0";
      checksum = "9/6a9330ad8d96f31e929feb414cde2959078379ba5a48c9e3eab34f280d7850eec6a0fa3ed5be9150e9e4d7df5139c1ae92f891b18167528553a11382d8f54183";
    };
    "redux-saga@npm:1.2.1" = {
      name = "redux-saga";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-1.2.1-4875573c97";
      outputHash = "a4e4f0d6df19738f494ca12814d0fc510a26ff25c1f1a810450dc3bbb89a3903870c941f08f465ce1ea2015e2e271e91d923c8e0932f066be9154d95f052ba83";
      flatName = "redux-saga";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.2.1";
      checksum = "9/a4e4f0d6df19738f494ca12814d0fc510a26ff25c1f1a810450dc3bbb89a3903870c941f08f465ce1ea2015e2e271e91d923c8e0932f066be9154d95f052ba83";
      dependencies = {
        "@redux-saga/core" = packages."@redux-saga/core@npm:1.2.1";
      };
    };
    "redux@npm:4.2.0" = {
      name = "redux";
      reference = "npm:4.2.0";
      linkType = "HARD";
      outputName = "redux-4.2.0-4688cc8d65";
      outputHash = "9239ab43da6a18375b413e128e9b808f28d46cbadfc58a371921396f82efd0187f17e6cd86c01080975c1778304b93a1546d735411067c54b1d81bd9e2e46307";
      flatName = "redux";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.4";
      checksum = "9/9239ab43da6a18375b413e128e9b808f28d46cbadfc58a371921396f82efd0187f17e6cd86c01080975c1778304b93a1546d735411067c54b1d81bd9e2e46307";
      dependencies = {
        "@babel/runtime" = packages."@babel/runtime@npm:7.20.1";
      };
    };
    "regenerator-runtime@npm:0.13.10" = {
      name = "regenerator-runtime";
      reference = "npm:0.13.10";
      linkType = "HARD";
      outputName = "regenerator-runtime-0.13.10-57e3c1406b";
      outputHash = "ac83ab4691a061519703e622ee817a0a517a80235d0c76a49ef32848c0d0946d97797d244806490f8f94e05a4b180a295869299b2e44c6f1c625b835703666a6";
      flatName = "regenerator-runtime";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.13.10";
      checksum = "9/ac83ab4691a061519703e622ee817a0a517a80235d0c76a49ef32848c0d0946d97797d244806490f8f94e05a4b180a295869299b2e44c6f1c625b835703666a6";
    };
    "resolve-from@npm:4.0.0" = {
      name = "resolve-from";
      reference = "npm:4.0.0";
      linkType = "HARD";
      outputName = "resolve-from-4.0.0-f758ec21bf";
      outputHash = "bc0ec65a95fae7d644cdb0f14e010c2cbde74d0844232542912f8343a20d66fc30a7b400391a0f118a710b9bc10078a0a13d8444a555f44c00023b3220249865";
      flatName = "resolve-from";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.0";
      checksum = "9/bc0ec65a95fae7d644cdb0f14e010c2cbde74d0844232542912f8343a20d66fc30a7b400391a0f118a710b9bc10078a0a13d8444a555f44c00023b3220249865";
    };
    "rimraf@npm:3.0.2" = {
      name = "rimraf";
      reference = "npm:3.0.2";
      linkType = "HARD";
      outputName = "rimraf-3.0.2-2cb7dac69a";
      outputHash = "b786c9ad52df9fbcd9c7120e105f3150b83b39dd87d9235a93b0c7e806575e1e68936504ff64563dbe67b3f8bbbc00bdfff586157d402ee8990e7143456511c0";
      flatName = "rimraf";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.0";
      checksum = "9/b786c9ad52df9fbcd9c7120e105f3150b83b39dd87d9235a93b0c7e806575e1e68936504ff64563dbe67b3f8bbbc00bdfff586157d402ee8990e7143456511c0";
      bin = {
        "rimraf" = "bin.js";
      };
      dependencies = {
        "glob" = packages."glob@npm:7.2.3";
      };
    };
    "shebang-command@npm:2.0.0" = {
      name = "shebang-command";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "shebang-command-2.0.0-eb2b01921d";
      outputHash = "5907a8d5facbefbd4dc8d21778d2136d5d22d61b5526452d92d46662614f0ed57090e7adf7184fe9d2d5ef75af9f05d7573437e10b37f2e6fdeeeb5f59fd9ada";
      flatName = "shebang-command";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.0";
      checksum = "9/5907a8d5facbefbd4dc8d21778d2136d5d22d61b5526452d92d46662614f0ed57090e7adf7184fe9d2d5ef75af9f05d7573437e10b37f2e6fdeeeb5f59fd9ada";
      dependencies = {
        "shebang-regex" = packages."shebang-regex@npm:3.0.0";
      };
    };
    "shebang-regex@npm:3.0.0" = {
      name = "shebang-regex";
      reference = "npm:3.0.0";
      linkType = "HARD";
      outputName = "shebang-regex-3.0.0-899a0cd65e";
      outputHash = "6be1588a86ed74d05481d09a6ef6a8db44550fda9785ae08c3df06717abc2e5e9a11804b1d0ac9b0641870c5ebf545e18c8d348bc105ba09227e6a32415ea1d6";
      flatName = "shebang-regex";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.0";
      checksum = "9/6be1588a86ed74d05481d09a6ef6a8db44550fda9785ae08c3df06717abc2e5e9a11804b1d0ac9b0641870c5ebf545e18c8d348bc105ba09227e6a32415ea1d6";
    };
    "signal-exit@npm:3.0.7" = {
      name = "signal-exit";
      reference = "npm:3.0.7";
      linkType = "HARD";
      outputName = "signal-exit-3.0.7-bd270458a3";
      outputHash = "5cf7525c55a72d8d104d914acf2e470f74b2c156197277ad7b331bc5de3d8790170fed3c82ff98c7c31adaa8ff941bfd5ba44f55171cbe8ed0e939fa82a8322a";
      flatName = "signal-exit";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.7";
      checksum = "9/5cf7525c55a72d8d104d914acf2e470f74b2c156197277ad7b331bc5de3d8790170fed3c82ff98c7c31adaa8ff941bfd5ba44f55171cbe8ed0e939fa82a8322a";
    };
    "strip-ansi@npm:7.0.1" = {
      name = "strip-ansi";
      reference = "npm:7.0.1";
      linkType = "HARD";
      outputName = "strip-ansi-7.0.1-668c121204";
      outputHash = "552123468abae97929da64559af9c13f4518f8ea199038089bf5e49d7860d708e5e29b2e6401fcbab6f99f2c42f865c15a1976bcf51c5165f82152c7ce9a1043";
      flatName = "strip-ansi";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^7.0.1";
      checksum = "9/552123468abae97929da64559af9c13f4518f8ea199038089bf5e49d7860d708e5e29b2e6401fcbab6f99f2c42f865c15a1976bcf51c5165f82152c7ce9a1043";
      dependencies = {
        "ansi-regex" = packages."ansi-regex@npm:6.0.1";
      };
    };
    "strip-final-newline@npm:3.0.0" = {
      name = "strip-final-newline";
      reference = "npm:3.0.0";
      linkType = "HARD";
      outputName = "strip-final-newline-3.0.0-7972cbec8b";
      outputHash = "0b05a6bdafc591cf7d9eb40b74a976eeb0a65ce03b061436fc55a91e96572e0dd84f02efe24169cd3ec83691c448456370b40a3c852acc45e61af0782a797987";
      flatName = "strip-final-newline";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.0";
      checksum = "9/0b05a6bdafc591cf7d9eb40b74a976eeb0a65ce03b061436fc55a91e96572e0dd84f02efe24169cd3ec83691c448456370b40a3c852acc45e61af0782a797987";
    };
    "supports-color@npm:5.5.0" = {
      name = "supports-color";
      reference = "npm:5.5.0";
      linkType = "HARD";
      outputName = "supports-color-5.5.0-183ac537bc";
      outputHash = "2eca8c4c8fccd2bd0027af240f85e99b1c9cb221186288dd478ce0fc61bdc07394e47f1bba2c91fe3ae432764772e3639e9c48bef19817267f151ae4a9b9ebef";
      flatName = "supports-color";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^5.3.0";
      checksum = "9/2eca8c4c8fccd2bd0027af240f85e99b1c9cb221186288dd478ce0fc61bdc07394e47f1bba2c91fe3ae432764772e3639e9c48bef19817267f151ae4a9b9ebef";
      dependencies = {
        "has-flag" = packages."has-flag@npm:3.0.0";
      };
    };
    "tmp-promise@npm:3.0.3" = {
      name = "tmp-promise";
      reference = "npm:3.0.3";
      linkType = "HARD";
      outputName = "tmp-promise-3.0.3-6df4ad8df9";
      outputHash = "4ac6621136dbdff1a72621b95b7b8622414c446ccd82de8e89464937bc33d0d4af693b62afaa901f3564b75403c971a892ca396722a6bc7df97d187f21edcfaf";
      flatName = "tmp-promise";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.3";
      checksum = "9/4ac6621136dbdff1a72621b95b7b8622414c446ccd82de8e89464937bc33d0d4af693b62afaa901f3564b75403c971a892ca396722a6bc7df97d187f21edcfaf";
      dependencies = {
        "tmp" = packages."tmp@npm:0.2.1";
      };
    };
    "tmp@npm:0.2.1" = {
      name = "tmp";
      reference = "npm:0.2.1";
      linkType = "HARD";
      outputName = "tmp-0.2.1-a9c8d9c0ca";
      outputHash = "6d7e4d8985fc4b3ee2bc00cd00fb42a9be47d2542d0ebd5fcd9aa69fd9fc337fa949f7a1212cc7d4172559288bef30125787b7b4eca683c2b43c740fcc342a21";
      flatName = "tmp";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.2.0";
      checksum = "9/6d7e4d8985fc4b3ee2bc00cd00fb42a9be47d2542d0ebd5fcd9aa69fd9fc337fa949f7a1212cc7d4172559288bef30125787b7b4eca683c2b43c740fcc342a21";
      dependencies = {
        "rimraf" = packages."rimraf@npm:3.0.2";
      };
    };
    "typescript-compare@npm:0.0.2" = {
      name = "typescript-compare";
      reference = "npm:0.0.2";
      linkType = "HARD";
      outputName = "typescript-compare-0.0.2-86f99ed6e8";
      outputHash = "c9945b8084819b9bb7aa6a370d570cdc47b7498dc3f1aba16376d4d6f05c3ad7324c5f54903534f30986cfdec90775f281f6769f399aa9d77bcf54300f40cb92";
      flatName = "typescript-compare";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.0.2";
      checksum = "9/c9945b8084819b9bb7aa6a370d570cdc47b7498dc3f1aba16376d4d6f05c3ad7324c5f54903534f30986cfdec90775f281f6769f399aa9d77bcf54300f40cb92";
      dependencies = {
        "typescript-logic" = packages."typescript-logic@npm:0.0.0";
      };
    };
    "typescript-logic@npm:0.0.0" = {
      name = "typescript-logic";
      reference = "npm:0.0.0";
      linkType = "HARD";
      outputName = "typescript-logic-0.0.0-f343262bb5";
      outputHash = "3b2ed9aeb4a0abc7c422b46d0c09edae5053ddb0723e359b9e2f709655c5c42256cf9db0b390706f4066daaf46252900c95fd21f0b19a97d3e06e311addba219";
      flatName = "typescript-logic";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.0.0";
      checksum = "9/3b2ed9aeb4a0abc7c422b46d0c09edae5053ddb0723e359b9e2f709655c5c42256cf9db0b390706f4066daaf46252900c95fd21f0b19a97d3e06e311addba219";
    };
    "typescript-tuple@npm:2.2.1" = {
      name = "typescript-tuple";
      reference = "npm:2.2.1";
      linkType = "HARD";
      outputName = "typescript-tuple-2.2.1-b78fa3093a";
      outputHash = "53f3b380618ef56eb7c58f5cf027baf547416d8ef8145ac0b053e4f61bbef581c0f018393868e4cfa02c281d2250a9b8fd21d12615db992033e100702f4dea61";
      flatName = "typescript-tuple";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.2.1";
      checksum = "9/53f3b380618ef56eb7c58f5cf027baf547416d8ef8145ac0b053e4f61bbef581c0f018393868e4cfa02c281d2250a9b8fd21d12615db992033e100702f4dea61";
      dependencies = {
        "typescript-compare" = packages."typescript-compare@npm:0.0.2";
      };
    };
    "typescript@npm:4.9.1-beta" = {
      name = "typescript";
      reference = "npm:4.9.1-beta";
      linkType = "HARD";
      outputName = "typescript-4.9.1-beta-7ff573487c";
      outputHash = "e024fb9fb4abd95c2b2fa877ec9b3aab833a388690709d2e12aef0a9adc12be95fb2f9410b479a5b3c277c240b026e92e82227a5e4ece1868b57ce5be6f45cef";
      flatName = "typescript";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:4.9.1-beta";
      checksum = "9/e024fb9fb4abd95c2b2fa877ec9b3aab833a388690709d2e12aef0a9adc12be95fb2f9410b479a5b3c277c240b026e92e82227a5e4ece1868b57ce5be6f45cef";
      bin = {
        "tsc" = "bin/tsc";
        "tsserver" = "bin/tsserver";
      };
    };
    "typescript@patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>::version=4.9.1-beta&hash=7f4d21" = {
      name = "typescript";
      reference = "patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>::version=4.9.1-beta&hash=7f4d21";
      linkType = "HARD";
      outputName = "typescript-4.9.1-beta-36a8612e2f";
      outputHash = "54c08d930b680d1c892d5ad9e9fb4ba9d8b2c5e94d6cbbafd22112ba7248c113b0f05a48b07a1b5f6a2f6be904d9ec8ce691fe6cb2fdd864401b6437f0ff36c9";
      flatName = "typescript";
      languageName = "node";
      scope = null;
      descriptorRange = "patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>";
      checksum = "9/54c08d930b680d1c892d5ad9e9fb4ba9d8b2c5e94d6cbbafd22112ba7248c113b0f05a48b07a1b5f6a2f6be904d9ec8ce691fe6cb2fdd864401b6437f0ff36c9";
      bin = {
        "tsc" = "bin/tsc";
        "tsserver" = "bin/tsserver";
      };
    };
    "universalify@npm:2.0.0" = {
      name = "universalify";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "universalify-2.0.0-03b8b418a8";
      outputHash = "243b0697a640cda1912e62a79f9439ec24b937df9a9a47ee7dd5fe813c4547300a3dc346e0c7c10dbd925f54a19507e8de915f2562a5e694716bdcd0825d48f6";
      flatName = "universalify";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.0";
      checksum = "9/243b0697a640cda1912e62a79f9439ec24b937df9a9a47ee7dd5fe813c4547300a3dc346e0c7c10dbd925f54a19507e8de915f2562a5e694716bdcd0825d48f6";
    };
    "which@npm:2.0.2" = {
      name = "which";
      reference = "npm:2.0.2";
      linkType = "HARD";
      outputName = "which-2.0.2-320ddf72f7";
      outputHash = "3728616c789b289c36ba2572887145e0736f06fe3435b8fef17e27eb5ec0696f61a21e356dd7fa58486346e57186863afa1b6c27c7665f7e674c8124f7f61157";
      flatName = "which";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.1";
      checksum = "9/3728616c789b289c36ba2572887145e0736f06fe3435b8fef17e27eb5ec0696f61a21e356dd7fa58486346e57186863afa1b6c27c7665f7e674c8124f7f61157";
      bin = {
        "node-which" = "./bin/node-which";
      };
      dependencies = {
        "isexe" = packages."isexe@npm:2.0.0";
      };
    };
    "wrappy@npm:1.0.2" = {
      name = "wrappy";
      reference = "npm:1.0.2";
      linkType = "HARD";
      outputName = "wrappy-1.0.2-916de4d4b3";
      outputHash = "37d243a577dfeee20586eae1e3208dfb4e4cea1211a2a4116a19b50d91e619ff3dbc5ec934e28ca9baaa11a65df826c8d65c5fd1bb81f0ce0dadb469d47061c2";
      flatName = "wrappy";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1";
      checksum = "9/37d243a577dfeee20586eae1e3208dfb4e4cea1211a2a4116a19b50d91e619ff3dbc5ec934e28ca9baaa11a65df826c8d65c5fd1bb81f0ce0dadb469d47061c2";
    };
    "yaml@npm:1.10.2" = {
      name = "yaml";
      reference = "npm:1.10.2";
      linkType = "HARD";
      outputName = "yaml-1.10.2-0e780aebdf";
      outputHash = "d6f04384bdf1105256581aef39991f825e358f3f48f081974b0e0f39ff5240c60ccafb5842cb79d1287517efa2b9ee172c702f2e4855ba6cc46948b40a43aa6e";
      flatName = "yaml";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.10.0";
      checksum = "9/d6f04384bdf1105256581aef39991f825e358f3f48f081974b0e0f39ff5240c60ccafb5842cb79d1287517efa2b9ee172c702f2e4855ba6cc46948b40a43aa6e";
    };
  };
in
packages
